version: '3'
services:
  zookeeper:
    image: zookeeper:3.6.3
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - network

  kafka:
    image: confluentinc/cp-kafka:7.2.1
    container_name: kafka
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    networks:
      - network

  producer:
    build:
      context: ./producer
    container_name: producer
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=local
    depends_on:
      - kafka
    networks:
      - network

  consumer:
    build:
      context: ./consumer
    container_name: consumer
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=local
    networks:
      - network

  mockup:
    build:
      context: ./mockup
    container_name: mockup
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=local
    networks:
      - network

networks:
  network:
    driver: bridge