server:
  port: 8080

spring:
  application:
    name: consumer
  profiles:
    default: local
    active: local
  cloud:
    openfeign:
      client:
        config:
          slack:
            url: https://slack.com
            connect-timeout: 5000
            read-timeout: 5000