spring:
  kafka:
    bootstrap-servers: kafka:9092
  cloud:
    openfeign:
      client:
        config:
          slack:
            url: http://mockup:8080

logging:
  config: classpath:log4j2-local.xml