server:
  port: 8080

spring:
  application:
    name: consumer
  profiles:
    default: local
    active: local
  jackson:
    default-property-inclusion: non_null

logging:
  config: classpath:log4j2-local.xml