server:
  port: 8080

spring:
  application:
    name: producer
  profiles:
    default: local
    active: local
  jpa:
    properties:
      hibernate:
        ddl-auto: none
        format_sql: true
    open-in-view: false
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:db/migration, classpath:db/callback
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  jackson:
    default-property-inclusion: non_null