spring:
  datasource:
    url: jdbc:h2:mem:producer;DATABASE_TO_UPPER=false
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  kafka:
    bootstrap-servers: localhost:9092

logging:
  config: classpath:log4j2-local.xml